import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import educationRouter from "./education";
import experienceRouter from "./experience";
import portfolioRouter from "./portfolio";
import skillsRouter from "./skills";
import jobsRouter from "./jobs";
import applicationsRouter from "./applications";
import feedRouter from "./feed";
import postsRouter from "./posts";
import adminRouter from "./admin";
import authRouter from "./auth";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import messagingRouter from "./messaging";
import connectionsRouter from "./connections";
import bookmarksRouter from "./bookmarks";
import analyticsRouter from "./analytics";
import employeesRouter from "./employees";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(messagingRouter);
router.use(connectionsRouter);
router.use(bookmarksRouter);
router.use(analyticsRouter);
router.use(employeesRouter);
router.use(profilesRouter);
router.use(educationRouter);
router.use(experienceRouter);
router.use(portfolioRouter);
router.use(skillsRouter);
router.use(jobsRouter);
router.use(applicationsRouter);
router.use(feedRouter);
router.use(postsRouter);
router.use(adminRouter);
router.use(authRouter);

export default router;
