// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/saas-company-dashboard/Dashboard.tsx": () => import("../components/mockups/saas-company-dashboard/Dashboard.tsx"),
  "./components/mockups/saas-company-dashboard/DashboardLight.tsx": () => import("../components/mockups/saas-company-dashboard/DashboardLight.tsx")
};
